### ISSUE TITLE
new account is being created instead of signing in existing user

### ISSUE THREAD

**Issue by amitava82** [perrybutler/WP-OAuth#3]
Hello, thanks for the plugin! I justed installed and configured it and tried to login to my existing account using facebook/gmail. Both the cases It did not login into my existing account. Instead, it created new account. Is it the right functionality or am I missing something?

**Comment by codecowboy** [comment]
@amitava82 @perrybutler is there a workaround for now? I really need the accounts to be linked rather than creating a new account each time a user logs in. I'd rather use this plugin and help develop it rather than install something else. Thanks!

**Comment by amitava82** [comment]
I'm using another plugin for now for testing and waiting for the feature. My app is not in production yet so I don't mind wait for a while :)

**Comment by perrybutler** [comment]
@codecowboy that is not be intended behavior. Accounts will be linked, we just don't link existing accounts via email address.

I've been using WP-OAuth to login to my personal blog since the first version 0.1. I am positive that it does not create a new account each time.

The problem described by @amitava82 in this thread is related to already having registered users by the time you install WP-OAuth. In that case, the existing users won't get automatically linked to social accounts; instead a new account will be created for that social account. There is a workaround for this, by having your existing users login with their existing username/password, visiting the Your Profile page, and linking their social account there, which will effectively link the social account to the logged in WP user.

For example, when I register a new account at the [demo site](http://choiceschances.com) via the Login button at the top right, it will redirect me to the login provider (say Google) and prompt me to login there. When I login with Google, I will be prompted to grant WP-OAuth basic profile access (it won't have access to my email address). When I click Accept, I will be redirected back to the WordPress site and a WP user account will be created for me, linked to that Google account. Now whenever I logout of WP and return to the site later, I can just use Login with Google.

If you're having an issue that isn't covered by what I've said here, please post each step so I can try to reproduce it on my end. If I can't reproduce it on my end, I'd be willing to do some hands-on troubleshooting at your WP site to track down the issue.

**Comment by perrybutler** [comment]
Refer to issue #16
